### ISSUE TITLE
Repo title "Linux kernel 3.16 for MediaTek SoC" is out of date?

### ISSUE THREAD

**Issue by djkurtz** [mtk09422/chromiumos-third_party-kernel-mediatek#2]
I believe their are now two branches, with the most recent based on 3.18?

**Comment by NathanChung** [comment]
Please check branch 3.18 for MT8173 SoC.  Branch 3.16 is for MT8135 only.  Our DRM driver will be uploaded in branch 3.18 only.

**Comment by djkurtz** [comment]
Yes, I understand that; just suggesting you can update the repository name.

**Comment by NathanChung** [comment]
TItle is changed.  Thanks for your heads up.
